### Fetch list of tasks

GET http://localhost:3200/tasks
Content-Type: application/json

### create new task
POST http://localhost:3200/tasks
Content-Type: application/json

{
    "title":"Create api",
    "date":"2023-06-20T12:00:00Z",
    "description":"Test description",
    "priority":"normal",
    "status":"todo"
}
